-- DROP TABLE IF EXISTS user;
-- DROP TABLE IF EXISTS metric;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  fname TEXT NOT NULL,
  lname TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE metric (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  p_language TEXT NOT NULL,
  wpm INTEGER NOT NULL,
  cpm INTEGER NOT NULL,
  errors INTEGER NOT NULL,
  acc INTEGER NOT NULL,
  FOREIGN KEY (userId) REFERENCES user (id)
);


